# Generated by Django 5.2.7 on 2025-11-14 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_id', models.BigIntegerField()),
                ('rating', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('relation', models.CharField(choices=[('E', 'E'), ('S', 'S'), ('C', 'C'), ('I', 'I')], max_length=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='main.task')),
            ],
            options={
                'indexes': [models.Index(fields=['annotation_id'], name='main_annota_annotat_6bbb92_idx'), models.Index(fields=['task'], name='main_annota_task_id_fa6610_idx')],
            },
        ),
    ]
