# Generated by Django 3.2.25 on 2025-11-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.BigIntegerField(unique=True)),
                ('img', models.TextField()),
                ('query', models.TextField()),
                ('item', models.CharField(max_length=255)),
                ('it_name', models.TextField()),
                ('annotator', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['task_id'], name='main_datase_task_id_671ac2_idx'),
        ),
    ]
